$(function(){
	$('.booth').click
	(
		function(e)
		{
			if($(e.target).data('available'))
			{
				if($(e.target).hasClass('selected'))
				{
					$(e.target).removeClass('selected');
				}
				else
				{
					$('.selected').removeClass('selected');
					$(e.target).addClass('selected');
				}
			}
		}
	)
})